pportal/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.urls import reverse_lazy
#from django.views.generic import TemplateView

from django.contrib import admin
from django.contrib import auth
from django.contrib.auth import views as auth_views
from requests.forms import AnalysisForm, ProfileForm, Specimen_SGForm,Specimen_APMSForm,Specimen_PTMForm,Specimen_GBForm, EDForm
#from requests.views import AboutView,HomeView, CustomerRegistrationView,AnalysisRegistrationView, AnalysisForm, CustomerForm, Specimen_SGForm, ContactWizard
from requests.views import AboutView,HomeView, sample_deliveryView,contactView, AnalysisRegistrationView, questionsView, AnalysisForm,ExperimentForm,Specimen_SGForm, ContactWizardSG,ContactWizardPTM,ContactWizardAPMS,ContactWizardGB, LoginView,SGView#,ProjectRegistrationView
from django.views.generic import TemplateView
#from requests.views import AboutView,HomeView, AnalysisRegistrationView, AnalysisForm, CustomerForm, Specimen_SGForm, ContactWizard

from requests import views
#from requests.views import HomeView, AboutView, UserRegistrationView,AnalysisRegistrationView,SampleRegistrationView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sampledelivery/',  sample_deliveryView.as_view(template_name='sample-delivery3.html'),name='sample_delivery'),
    #url(r'^pportal/',include('pportal.urls')),
    url(r'^$', HomeView.as_view(template_name='home.html'), name='home'),
    url(r'^questions/',  questionsView.as_view(template_name='questions.html'),name='questions'),
    #url(r'^project-registration/$', ContactWizard.as_view([CustomerForm,AnalysisForm, Specimen_SGForm]),name='project-registration'),
    #url(r'^project-registration/$', ContactWizard.as_view([AnalysisForm, Specimen_SGForm, ExperimentForm]),name='project-registration'),
    #url(r'^project-registration/$', HomeView.as_view(template_name='home.html') ,name='project-registration'),
    #url(r'^project-registrationsg/$', ContactWizardSG.as_view([AnalysisForm, Specimen_SGForm, ExperimentForm]),name='projectregistrationsg'),
    #url(r'^project-registrationsg/$', 'projectregistrationsg',name='projectregistrationsg'),
    url(r'^project-registrationsg/$', ContactWizardSG.as_view([AnalysisForm, Specimen_SGForm, ExperimentForm]),name='projectregistrationsg'),
    url(r'^project-registrationapms/$', ContactWizardAPMS.as_view([AnalysisForm, Specimen_APMSForm, ExperimentForm]),name='projectregistrationapms'),
    url(r'^project-registrationptm/$', ContactWizardPTM.as_view([AnalysisForm, Specimen_PTMForm, ExperimentForm]),name='projectregistrationptm'),
    url(r'^project-registrationgb/$', ContactWizardGB.as_view([AnalysisForm, Specimen_GBForm, ExperimentForm]),name='projectregistrationgel'),
    #url(r'^profile/(?P<email>[a-zA-Z0-9]+)/$', views.get_user_profile, name='profile'),
    #url(r'^profile/$', views.get_user_profile, name='profile'),
    url(r'^project-registration/$', login_required(views.get_user_profile), name='projectregistration'),
    url(r'^requestt_page/$', views.requestt_page, name='requestt_page'),
    #url(r'^project-registration/$', views.get_user_profile, name='projectregistration'),
    url(r'^contact/',  contactView.as_view(template_name='contact.html'),name='contact'),
    #url(r'^project-info/$', views.get_user_projectinfo, name='projectinfo'),
    #url(r'^profile/(?P<email>\w+)/$', views.get_user_profile, name='profile'),
    url(r'^about/$', AboutView.as_view(template_name='about.html'),name='about'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html'),name='bootstrap'),
    url(r'^login/$', LoginView.as_view(template_name='login.html'),name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page=reverse_lazy('login')),name='logout'),
    url(r'^sgform/$', SGView.as_view(template_name='project-regis_sg.html'),name='sg_form'),
    #url(r'^logout/$', auth_views.logout,{'next_page':'/'},name='logout'),
    #url(r'^logout/$', auth_views.logout,{template_name:'logout.html'},name='logout'),
    #url(r'^login/$', auth.auth_views.login,name='login'),
    #url(r'^login/$', LoginView.as_view(template_name='login.html'),name='login'),
    # url(r'^project-registration/$', RegistrationView.as_view()),
    #url(r'^project-registration/$', CustomerRegistrationView.as_view(template_name='project-registration_2.html')),
    #url(r'^project-registration-2/$', AnalysisRegistrationView.as_view(template_name='project-registration_2.html')),
    #static(settings.STATIC_URL,document_root =settings.STATIC_ROOT),
    #url(r'^project-registration-3/$', AnalysisRegistrationView2.as_view(template_name='project-registration.html')),
    #url(r'^project-registration-5/$', views.manage_users, name='manage_users'),
    #url(r'^project-registration-3/$', ExperimentalDesignRegistrationView.as_view(template_name='project-registration.html')),
]

# if DEBUG is on
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root =settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

requests/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.files.storage import FileSystemStorage
import os
from django.contrib.auth.models import (AbstractBaseUser,
	BaseUserManager)
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.
# Create your models here.

class UserManager(BaseUserManager):
	def get_by_natural_key(self, email):
		return self.get(email=email)
	def create_user(self,email,password=None, is_active=True,is_staff=False,is_admin=False):
		if not email:
			raise ValueError("You must provide an email address")
		if not password:
			raise ValueError("You must provide a password")
		user_obj = self.model(
			email=self.normalize_email(email)
		)
		user_obj.set_password(password)
		user_obj.active = is_active
		user_obj.staff = is_staff
		user_obj.admin = is_admin
		user_obj.save(using=self._db)
		return user_obj

	def create_staff_user(self,email,password=None):
		user_obj = self.create_user(
			email, password=password,
			is_staff=True
		)
		return user_obj

	def create_superuser(self,email,password=None):
		user_obj = self.create_user(
			email, password=password,
			is_staff=True,
			is_admin=True
		)
		return user_obj


class User(AbstractBaseUser):
	email = models.EmailField(unique=True, max_length=120)
	active = models.BooleanField(default=True)
	staff = models.BooleanField(default=False)
	admin = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True)
	USERNAME_FIELD='email'
	REQUIRED_FIELD=[]
	objects= UserManager()
	def __str__(self):
		return self.email
	def get_full_name(self):
		return self.email
	def get_short_name(self):
		return self.email
	def get_username(self):
		return self.email
	def get_last_name(self):
		return self.email
	def has_perm(self, perm,obj=None):
		return True
	def has_module_perms(self, app_label):
		return True
	@property
	def is_staff(self):
		return self.staff
	@property
	def is_admin(self):
		return self.admin

STUDYTYPES = (
	('VIB','VIB'),
	('Academic','Academic'), 
	('Non-Academic','Non Academic'),
	)

#  class 1 - form 1
# ANALYSISTYPES = (
# 	('shotgun','Shotgun analysis'),
# 	('APMS','Affinity-Purification MS (AP-MS)'), 
# 	('PTMs','PTM analysis'),
# 	('gelband','Protein gel band analysis'),
# 	('proteinmass','Protein mass determination'),
# 	('other','Other'),
# 	)


class Profile(models.Model):
	ANALYSISTYPES = (
	('shotgun','Shotgun analysis'),
	('APMS','Affinity-Purification MS (AP-MS)'), 
	('PTMs','PTM analysis'),
	('gelband','Protein gel band analysis'),
	('proteinmass','Protein mass determination'),
	('other','Other'),
	)

	Issue = models.CharField(max_length=200, blank=True)
	user=models.OneToOneField(User, on_delete=models.CASCADE)
	Name = models.CharField(max_length=120)
 	# Emailadress = models.EmailField(max_length=120)
	Study_Type = models.CharField(max_length=50, choices=STUDYTYPES)
	Group_Leader = models.CharField(max_length=120)
	Analysis_Type = models.CharField(max_length=50 , choices=ANALYSISTYPES)
	timestamp = models.DateTimeField(auto_now_add=True)
	def __unicode__(self):
		return self.Name
	def __str__(self):
		return self.Name
	def getAnalysisType(self):
		return dict(Profile.ANALYSISTYPES)[self.Analysis_Type]

@receiver(post_save, sender=User)
def create_user_profile(sender,instance,created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender,instance, **kwargs):
	instance.profile.save()


DATAANALYSIS = (
	(True,'Yes'),
	(False,'No')
	)

SAMPLETYPES = (
	('cell_pellet','cell pellet'),
	('tissue','tissue'), 
	('protein_extract','protein extract'),
	)

VUNITS = (
	(True,'μl'),
	(False,'ml'),
	)
CUNITS = (
	('nmol/ul','ng/μl'),
	('umol/ul','μg/μl'),
	('mmol/ul','mg/μl'),
	)
BAITS = (
	(True,'a protein'),
	(False,'another type of molecule'),
	)
SAMPLETYPESAPMS = (
	(True,'washed beads'),
	(False,'eluate'),
	)
PAGETYPES = (
	(True,'SDS-PAGE'),
	(False,'native PAGE'),
	)
GBCHOICES = (
	(True,'loaded on gel'),
	(False,'estimate about gel band'),
	)

class Analysis(models.Model):
	Project_summary = models.CharField(max_length=300)
	Project_keywords = models.CharField(max_length=120)
	#Analysis_type = models.CharField(max_length=50,default=None , choices=ANALYSISTYPES)
	#Data_analysis = models.BooleanField(choices=DATAANALYSIS)
	#Data_analysis = models.BooleanField()
#class Profile_extra(models.Model):
	Affiliation = models.CharField(max_length=120)
	Address = models.CharField(max_length=300)
	#def __unicode__(self):
	#	return self.Name
	def __unicode__(self):
		return self.Project_summary


# shotgun Specimen
class Specimen_SG(models.Model):
	Species = models.CharField(max_length=120)
	Taxon_id = models.CharField(max_length=120)
	Sequence_Database_Public_Availability = models.BooleanField(choices=DATAANALYSIS, null=False,
		default=True)
	Sequence_Database_Source = models.CharField(max_length=50)
	Sequence_Database_File = models.FileField(storage=FileSystemStorage(location=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'media')))
	##Other_Relevant_
	##Other_Sequence_Database_File = models.FileField(upload_to='seqdbs')

	#Sample_Type_Delivered 
	Sample_Type = models.CharField(max_length=50 ,choices=SAMPLETYPES, null=False, default='cell pellet')
	Sample_Vial = models.CharField(max_length=120)
	# if applicable exact
	Buffer_Composition = models.CharField(max_length=300)
	#volume or estimation in ul / ml
	Volume = models.FloatField()
	VUnit = models.BooleanField(choices=VUNITS, default='μl', null=False,)
	Protein_Concentration = models.FloatField()
	CUnit = models.CharField(max_length=10 , choices=CUNITS,null=False,default='μg/μl', blank=False)
	def __unicode__(self):
		return self.Species 	
	def get_absolute_url(self):
		return reverse('pportal:home')

# PTM Specimen
class Specimen_PTM(models.Model):
	Modification_Under_Investigation = models.CharField(max_length=120)
	Species = models.CharField(max_length=120)
	Taxon_id = models.CharField(max_length=120)
	Sequence_Database_Public_Availability = models.BooleanField(choices=DATAANALYSIS, null=False,
		default=True)
	Sequence_Database_Source = models.BooleanField()
	Sequence_Database_File = models.FileField()
	#Sample_Type_Delivered 
	Sample_Type = models.CharField(max_length=50 ,choices=SAMPLETYPES)
	Sample_Vial = models.CharField(max_length=120)
	Buffer_Composition = models.CharField(max_length=300)
	#volume or estimation in ul / ml
	Volume = models.FloatField()
	VUnit = models.BooleanField(choices=VUNITS)
	Protein_Concentration = models.FloatField()
	CUnit = models.CharField(max_length=10 , choices=CUNITS)
	def __unicode__(self):
		return self.Species 	

# AP-MS Specimen
class Specimen_APMS(models.Model):
	Bait_Molecule = models.BooleanField(choices=BAITS)
	# if protein 
	# antibodies used for IP
	IPAntibodies_names = models.CharField(max_length=120)
	# if applicable
	IPAntibodies_Supplier = models.CharField(max_length=120) 
	IPAntibodies_CatalogNumber = models.CharField(max_length=120)
	# amount or estimate
	Species = models.CharField(max_length=120)
	Taxon_id = models.CharField(max_length=120)
	Sequence_Database_Public_Availability = models.BooleanField(choices=DATAANALYSIS, null=False,
		default=True)
	Sequence_Database_Source = models.BooleanField()
	Sequence_Database_File = models.FileField()
	#Sample_Type_Delivered 
	Sample_Type = models.BooleanField(max_length=50, choices=SAMPLETYPESAPMS)
	Sample_Vial = models.CharField(max_length=120)
	Buffer_Composition = models.CharField(max_length=300)
	#volume or estimation in ul / ml
	Volume = models.FloatField()
	VUnit = models.BooleanField(choices=VUNITS)
	Protein_Concentration = models.FloatField()
	CUnit = models.CharField(max_length=10 , choices=CUNITS)
	def __unicode__(self):
		return self.Species 	

# Gelband Specimen
class Specimen_GB(models.Model):
	Experimental_Setup_Sample_Preparation = models.TextField(max_length=300) 
	Gel_GelBand_Image = models.FileField()
	Species = models.CharField(max_length=120)
	Taxon_id = models.CharField(max_length=120)
	Sequence_Database_Public_Availability = models.BooleanField(choices=DATAANALYSIS, null=False,
		default=True)
	Sequence_Database_Source = models.BooleanField()
	Sequence_Database_File = models.FileField()
	#Sample_Type_Delivered 
	Gel_Type = models.TextField(max_length=300)
	Gel_Supplier = models.CharField(max_length=120) 
	Gel_CatalogNumber = models.CharField(max_length=120)
	Gel_Staining_Method = models.CharField(max_length=120)
	Electrophoresis_Type = models.BooleanField(choices=PAGETYPES)
	Sample_Vial = models.CharField(max_length=120)
	# or estimation of
	Amount_Of_Protein_Loaded = models.CharField(max_length=300)
	Amount_Of_Protein_Loaded_Type = models.BooleanField(choices=GBCHOICES)
	#volume or estimation in ul / ml
	CUnit = models.CharField(max_length=10, choices=VUNITS, null=False,
		default=True)
	def __unicode__(self):
		return self.Species 	

# reference: Django documentation
# examples/one_to_one

class Experiment(models.Model):
	#def __init__(self):
	Isotopic_labeling = models.BooleanField(choices=DATAANALYSIS, null=False,
		default=True)
	Isotopic_labeling_details = models.CharField(max_length=20, blank=True)
	Nb_factors = models.IntegerField(blank=False, default = 1)
	Nb_conditions = models.IntegerField(blank=False, default = 1)
	# maybe instantiate another model called efactor (experimental factor) n times, n (Nb_factors)
	Factor_name_lst = models.CharField(max_length=120, null=True)
	Conditions_list = models.CharField(max_length=120, null=True)
	Nb_samples = models.IntegerField(blank=False, default = 0)
	Generic_Sample_Name = models.CharField(max_length=120, null=False)
	Sample_Name = models.CharField(max_length=120, null=True)
	# getmehods



#class 2 - form 1
# class Sample(models.Model): # biological specimen
# 	#def __init__(self):
# 	#Experiment.__init__(self)
# 	#experiment = models.OneToOneField(Experimental_Design, 

templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load staticfiles %}

<html lang="en" ng-app="cfe">

<head>

    <meta charset="utf-8" />
    <!-- <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png"> -->

   
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
{% block head_title %}VIB Proteomics Core{% endblock head_title %} 
</title>
{% include 'snippets/css.html' %}

</head>

<body font-family:"OpS">
{% include 'snippets/nav.html' %}

     	  
{% block content %}
{% endblock %} 


{% block content2 %}


{% endblock %}



{% include 'snippets/js.html' %}

</body>
<br>
{% block content3 %}
 {% include 'snippets/foot.html' %} 
 {% endblock %}
</html>

templates/contact.html
<!-- contact-->
{% extends "base.html" %}

{% block head_title %}Contact || {{ block.super }}{% endblock head_title %}

{% block content2 %}

{# Load the tag library #}

{% load bootstrap4 %}
{# Display a form #}

<div class='container'>
<div class="row">
    <div class="col-12 ml-auto">

      <h5 class="frb">Contact</h5>

      <br>
      <a href="https://corefacilities.vib.be/pec" class="indent">Website</a>

      <ul class="cn">
        <li>Email: pec@vib-ugent.be</li>
        <li>Phone: +32 9 264 93 60</li>
        <li>Shipping Address:
        	<div class ="ab">VIB Center for Medical Biotechnology</div>
        	<div class = "ab">Albert Baertsoenkaai 3</div>
        	<div class = "ab">9000 Ghent - Belgium</div>

        </li>
        <li>When delivering the samples in person: <div class="ab"> Use the entrance at the Apotheekstraat. And go to the glass building in front of you. </div></li>
          <br>
          <img src='Entrance.png' alt="Entrance image">
          <br>
      </ul>
    
      <img src="">
      <div class="alert" style='min-height: 800px;'>
      </div>
</div>

{% endblock %}

templates/done.html
{% extends 'base.html' %}

{% block content2 %}

<div class='container'>
<div class="row">
     <div class="col-12 ml-auto">

<h5>Your registration was successfull! Thank you.</h5>


	{{ analysis }}
	<br>
	{{ upload_file  }}
	<br>

{% for form in form_data %}
	{{ form }}
{% endfor %}
       <div class="col-4">
                    <div class="alert" style='min-height: 400px;'>
          </div>
         </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block head_title %}Welcome || {{ block.super }}{% endblock head_title %}

{% block content2 %}
<div class='container'>
<div class="row">
  <div class="col-12 ml-auto">


		<h5 class="frb">Welcome to the VIB Proteomics Core portal!</h5>

    <p class="fr">This website is a an extension of our facility's<a href="https://corefacilities.vib.be/pec"> main page</a> and serves 2 goals:</p>
    <ul class="ab">
      <li>As a registration platform for your proteomics project</li>
      <li>As an access point to follow the progress of your experiment</li>
    </ul>
    
    <br/>
    <p class="fr">If you want your samples to be analyzed by the VIB Proteomics core, please use the workflow below.</p>


    <div class="container">
      <div id="accordion">
        <div class="card">
          <div class="card-header">
            <a class="card-link" data-toggle="collapse" href="#collapseOne">
              1. Contact the facility at an early stage and announce delivery
            </a>
          </div>
          <div id="collapseOne" class="collapse show" data-parent="#accordion">
            <div class="card-body">
              <p class = "indent">
              Before sending samples to the Facility, <a href="{% url 'contact' %}">contact us</a> in an early stage so your specific question can be discussed.</p>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <a class="collapsed card-link" data-toggle="collapse" href="#collapseTwo">
              2. Register your project
            </a>
          </div>
          <div id="collapseTwo" class="collapse" data-parent="#accordion">
            <div class="card-body">
              <p class = "indent">
                When the project is accepted, you will receive a login to access <a href="{% url 'projectregistration' %}">the sample registration tab </a>. 
              </p>
              <p class = "indent">
                There you have to complete the form with all the information about the experiment you’re about to send. 
              </p>
              <p class = "text-secondary">
                <span class = "font-weight-bold">Note:</span> Please try to fill in all the fields. That way, we can understand the goals and expectations of your experiment. </p>
            </div> 
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <a class="collapsed card-link" data-toggle="collapse" href="#collapseThree">
              3. Send your sample according to the sample delivery guidelines
            </a>
          </div>
          <div id="collapseThree" class="collapse" data-parent="#accordion">
            <div class="card-body">
              <p class = "indent">
              After project registration, arrangements on delivery date can be made with the Proteomics Core. All instructions can be found <a href="{% url 'sample_delivery' %}">here</a>. </p>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <a class="collapsed card-link" data-toggle="collapse" href="#collapseFour">
              4. Follow your project
            </a>
          </div>
          <div id="collapseFour" class="collapse" data-parent="#accordion">
            <div class="card-body">
              <p class = "indent">
              During sample processing we will update the status of your project. This can be followed in the project status tab. </p>
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            <a class="collapsed card-link" data-toggle="collapse" href="#collapseFive">
              5. Check the results
            </a>
          </div>
          <div id="collapseFive" class="collapse" data-parent="#accordion">
            <div class="card-body">
              <p class = "indent">
              The results of the analysis will be send to you from the moment the data-analysis is finished. If you have quenstions, you can always check our <a href="{% url 'questions' %}"> frequentlty asked questions</a> tab. Don't hesitate to <a href="{% url 'contact' %}">contact us</a> if your questions are not solved.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

       <div class="col-4">
                    <div class="alert" style='min-height: 400px;'>
          </div>
         </div>
  {% endblock %}	
         

from home show templateview()

templates/login.html
{% extends "base.html" %}

{% block head_title %}Login|| {{ block.super }}{% endblock head_title %}

{% block content2 %}

{# Load the tag library #}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{# Display a form #}
<div class='container'>
<div class="row">
     <div class="col-1">
     <div class="alert" style='min-height: 800px;'>
  </div>
</div>

<div class="col-4 col-md-4 col-lg-4">
</br>
<form action= "" method = "POST">
	{% csrf_token %}
	{{ form|crispy }}
	{% buttons %}
		<button type="submit" class="btn btn-sm">Login</button>
	{% endbuttons %}
</div>
</form>
  </div>
           <div class="col-7">
           	        <div class="alert" style='min-height: 800px;'>
          </div>
         </div>
  </div>
  </div>
{% endblock %}

templates/project-regis.html
{% extends "base.html" %}
{% load i18n %}


{% block head_title %}Project Registration || {{ wizard.form.media }}{{ block.super }}{% endblock head_title %}


{# Load the tag library #}


{# Display a form #}


{% block content2 %}

 <div class='container'>
<div class="row">

<div class="col-8 col-md-8 col-lg-6 mr-auto">
<form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
{{ wizard.management_form }}
{% load crispy_forms_tags %}
{% if wizard.form.forms %}
{% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}
      {{ field }}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}
    {{ wizard.form.management_form }}
        {{ wizard.form|crispy }}
        <div class="input-group"> <input type="number" name="Volume" step="any" required="" class="numberinput form-control" id="id_Volume"> <span class="input-group-addon">μl</span> </div>
{% else %}
       {{ wizard.form|crispy }}

{% endif %}



{% if wizard.steps.prev %}
<button name="wizard_goto_step" type="submit" class="btn btn-sm" value="{{ wizard.steps.first }}">{% trans "first step" %}</button>
<button name="wizard_goto_step" type="submit" class="btn btn-sm" value="{{ wizard.steps.prev }}">{% trans "prev step" %}</button>
{% endif %}
{% if wizard.steps.last %}
<input type="submit" class="btn btn-sm" value="submit"/>
{% else %}
<button name="wizard_goto_step" type="submit" class="btn btn-sm" value="{{ wizard.steps.next }}">{% trans "next step" %}</button>
{% endif %}
</form>
<p><i><font size="2.8">Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }} </font></i></p>
  </div>
           <div class="col-3">
           	        <div class="alert" style='min-height: 800px;'>
          </div>
         </div>
  </div>
  </div>	
{% endblock %}

templates/project-regis_o.html
?

{% extends "base.html" %}
{% load i18n %}


{% block head_title %}Project Registration || {{ wizard.form.media }}{{ block.super }}{% endblock head_title %}


{# Load the tag library #}


{# Display a form #}


{% block content2 %}

<div class='container'>
<div class="row">

<div class="col-8 col-md-8 col-lg-6 mr-auto">
<form action="" method="get">{% csrf_token %}
{% load crispy_forms_tags %}
<h6>Form Registration</h6>
{{ form|crispy }}

<input type="submit" class="btn btn-sm" value="submit"/>

</form>


  </div>
           <div class="col-3">
           	        <div class="alert" style='min-height: 800px;'>
          </div>
         </div>
  </div>
  </div>	
{% endblock %}

templates/project-regis_oo.html
?

{% extends "base.html" %}
{% load i18n %}


{% block head_title %}Project Registration || {{ wizard.form.media }}{{ block.super }}{% endblock head_title %}


{# Load the tag library #}


{# Display a form #}


{% block content2 %}

 <div class='container'>
<div class="row">

<div class="col-8 col-md-8 col-lg-6 mr-auto">
<h7>Form Registration</h7>
<form action="#" method = "get">

	  <p>Please fill-in the experimental design file template presented below and then submit the finalized version.</p>
  <input type="submit" class="btn btn-default btn-sm pull-right" name="excel" value="Download experimental design file"></input>
  </form>
<form action="#" method = "get">
	{% load crispy_forms_tags %}
{{ form|crispy }}
</form>
<form action="#" onsubmit="if(document.getElementById('agree').checked) { return true; } else { alert('Please indicate that you have read and agree to the Terms and Conditions'); return false; }">
<p><b>Terms and Conditions</b></p>
<input type="checkbox" name="checkbox" value="check" id="agree" /> I have agreed to acknowledge the VIB Protemics Core in any publications...
<input type="submit" name="submit" value="submit" />

</form>
  </div>
           <div class="col-3">
           	        <div class="alert" style='min-height: 800px;'>
          </div>
         </div>
  </div>
  </div>

{% endblock %}

templates/questions.html
{% extends "base.html" %}

{% block head_title %}Welcome || {{ block.super }}{% endblock head_title %}

{% block content2 %}
<div class='container'>
<div class="row">
  <div class="col-12 ml-auto">


  <h5 class="frb">Frequently asked questions</h5>

  {% endblock %}	
         

from home show templateview()